<?php
return array(
'version'=> 'Alpha 1.0',
'siteDesc'=> '',
'address'=> '重庆市江北观音桥',
'phone'=> '023-12345678',
'email'=> 'admin@admin.com',
'beian'=> '渝备12345678',
'copyright'=> '2012-2013',
'siteKeywords'=> '',
'imgMaxSize'=> '1024000',
'imgThumbSize'=> '124,200,300,600,origin',
'imgAllowTypes'=> '*.jpg;*.png;*.jpeg',
'imgMinHeight'=> '300',
'imgUploadNum'=> '10',
'imgMinWidth'=> '300',
'indexpage'=> '4@ads|13#4@ads|13#4@ads|13',
'domain'=> 'http://localhost',
'shortTitle'=> '带上新的生活去旅行',
'sitename'=> '新灵旅行',
'userDefaultGroup'=> '6',
'shopGroupId'=> '7',
'forbidnotshop'=> '0',
'adminGroupIds'=> '5,4',
'officalUid'=> '',
'validateEmail'=> '1',
'validateEmailGroup'=> '7',
'baseurl'=> 'http://localhost/huixiao/',
'badwords'=> '呵呵#哈哈#嘿嘿',
'checkBadWords'=> '1',
'imgQuality'=> '80',
'hotsearchs'=> '呵呵#哈哈#嘿嘿',
'orderByTop'=> '0',
'closeSiteReason'=> '系统正在维护中，请稍后再访问！',
'mobile'=> '1',
'closeSite'=> '1',
'noticeall'=> '近期收到举报，有部分网站有不良信息，望各位店家及时处理！',
'badwordsHandleStyle'=> 'filter',
);
?>